// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry             = require("bs-platform/lib/js/curry.js");
var HelpCommand$Hwan  = require("./commands/HelpCommand.js");
var InitCommand$Hwan  = require("./commands/InitCommand.js");
var BuildCommand$Hwan = require("./commands/BuildCommand.js");

function execute(args) {
  if (args) {
    switch (args[0]) {
      case "build" : 
          return Curry._1(BuildCommand$Hwan.command[/* exec */3], args[1]);
      case "init" : 
          return Curry._1(InitCommand$Hwan.command[/* exec */3], args[1]);
      default:
        return Curry._1(HelpCommand$Hwan.command[/* exec */3], /* [] */0);
    }
  } else {
    return Curry._1(HelpCommand$Hwan.command[/* exec */3], /* [] */0);
  }
}

exports.execute = execute;
/* HelpCommand-Hwan Not a pure module */
