// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Arg   = require("bs-platform/lib/js/arg.js");
var List  = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");

function parseScript(param) {
  if (param) {
    var match = param[1];
    if (match) {
      var script = match[0];
      if (script === "run") {
        var match$1 = match[1];
        if (match$1) {
          return match$1[0];
        } else {
          return script;
        }
      } else {
        return script;
      }
    } else {
      return "no such a fucking command";
    }
  } else {
    return "no such a fucking command";
  }
}

function parse() {
  var version = [/* false */0];
  var $$package = [""];
  var anon = [/* [] */0];
  var prepend = function (a) {
    anon[0] = /* :: */[
      a,
      anon[0]
    ];
    return /* () */0;
  };
  var speclist_000 = /* tuple */[
    "-v",
    /* Set */Block.__(2, [version]),
    "Show version"
  ];
  var speclist_001 = /* :: */[
    /* tuple */[
      "--version",
      /* Set */Block.__(2, [version]),
      "Show version"
    ],
    /* :: */[
      /* tuple */[
        "--hwan-pkg",
        /* Set_string */Block.__(5, [$$package]),
        "Script execution target"
      ],
      /* [] */0
    ]
  ];
  var speclist = /* :: */[
    speclist_000,
    speclist_001
  ];
  Arg.parse(speclist, prepend, "Minimalistic monorepo management tool");
  return /* tuple */[
          parseScript(List.rev(anon[0])),
          /* record */[
            /* version */version[0],
            /* package */$$package[0]
          ]
        ];
}

exports.parseScript = parseScript;
exports.parse       = parse;
/* No side effect */
