// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Arg        = require("bs-platform/lib/js/arg.js");
var List       = require("bs-platform/lib/js/list.js");
var Block      = require("bs-platform/lib/js/block.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function parse() {
  var version = [/* false */0];
  var $$package = [""];
  var anon = [/* [] */0];
  var prepend = function (a) {
    anon[0] = /* :: */[
      a,
      anon[0]
    ];
    return /* () */0;
  };
  var speclist_000 = /* tuple */[
    "--version",
    /* Set */Block.__(2, [version]),
    "Show version"
  ];
  var speclist_001 = /* :: */[
    /* tuple */[
      "--package",
      /* Set_string */Block.__(5, [$$package]),
      "Script execution target"
    ],
    /* [] */0
  ];
  var speclist = /* :: */[
    speclist_000,
    speclist_001
  ];
  var usagemsg = "Minimalistic monorepo management tool";
  Arg.parse(speclist, prepend, usagemsg);
  var command = List.tl(List.rev(anon[0]));
  var match = version[0];
  var exit = 0;
  if (command || match !== 0) {
    exit = 1;
  } else {
    Arg.usage(speclist, usagemsg);
    Pervasives.exit(0);
  }
  +(exit === 1);
  return /* tuple */[
          command,
          /* record */[
            /* version */version[0],
            /* package */$$package[0]
          ]
        ];
}

exports.parse = parse;
/* No side effect */
