// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Fs           = require("fs");
var Glob         = require("glob");
var Path         = require("path");
var $$Array      = require("bs-platform/lib/js/array.js");
var Process      = require("process");
var Pervasives   = require("bs-platform/lib/js/pervasives.js");
var Config$Hwan  = require("./Config.js");
var Logging$Hwan = require("./Logging.js");
var Package$Hwan = require("./Package.js");

function isProjectRoot(path) {
  return +Fs.existsSync(Path.join(path, Config$Hwan.packageJson));
}

function findRootDir(_cwd, _root, _param) {
  while(true) {
    var root = _root;
    var cwd = _cwd;
    var root_ = root ? root[0] : Path.parse(cwd).root;
    if (isProjectRoot(cwd)) {
      return cwd;
    } else if (cwd !== root_) {
      _param = /* () */0;
      _root = /* Some */[root_];
      _cwd = Path.dirname(cwd);
      continue ;
      
    } else {
      Logging$Hwan.err("Could find the project root directory.");
      return Pervasives.exit(1);
    }
  };
}

function collectPackages() {
  var rootDir = findRootDir(Process.cwd(), /* None */0, /* () */0);
  return $$Array.map(Package$Hwan.concretizePackage, Glob.sync(Config$Hwan.packagePaths, {
                  cwd: rootDir,
                  absolute: /* true */1
                }));
}

exports.isProjectRoot   = isProjectRoot;
exports.findRootDir     = findRootDir;
exports.collectPackages = collectPackages;
/* fs Not a pure module */
