// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


var packagePaths = "packages/*";

var packageJson = "package.json";

exports.packagePaths = packagePaths;
exports.packageJson = packageJson;
/* No side effect */
