// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Printf = require("bs-platform/lib/js/printf.js");

function err(msg) {
  return Curry._1(Printf.eprintf(/* Format */[
                  /* String_literal */Block.__(11, [
                      "[hwan] warning: ",
                      /* String */Block.__(2, [
                          /* No_padding */0,
                          /* Char_literal */Block.__(12, [
                              /* "\n" */10,
                              /* Flush */Block.__(10, [/* End_of_format */0])
                            ])
                        ])
                    ]),
                  "[hwan] warning: %s\n%!"
                ]), msg);
}

function output(msg) {
  return Curry._1(Printf.printf(/* Format */[
                  /* String_literal */Block.__(11, [
                      "[hwan] output:\n",
                      /* String */Block.__(2, [
                          /* No_padding */0,
                          /* Char_literal */Block.__(12, [
                              /* "\n" */10,
                              /* End_of_format */0
                            ])
                        ])
                    ]),
                  "[hwan] output:\n%s\n"
                ]), msg);
}

function log(type_, msg) {
  return Curry._2(Printf.printf(/* Format */[
                  /* String_literal */Block.__(11, [
                      "[hwan] ",
                      /* String */Block.__(2, [
                          /* No_padding */0,
                          /* String_literal */Block.__(11, [
                              ": ",
                              /* String */Block.__(2, [
                                  /* No_padding */0,
                                  /* Char_literal */Block.__(12, [
                                      /* "\n" */10,
                                      /* End_of_format */0
                                    ])
                                ])
                            ])
                        ])
                    ]),
                  "[hwan] %s: %s\n"
                ]), type_, msg);
}

function logCommand(command) {
  return log("Executing Command", List.fold_left((function (s1, s2) {
                    return s1 + (" " + s2);
                  }), "", command));
}

function logPackage($$package) {
  var tmp = $$package === "" ? "all" : $$package;
  return log("Package", tmp);
}

exports.err = err;
exports.output = output;
exports.log = log;
exports.logCommand = logCommand;
exports.logPackage = logPackage;
/* No side effect */
