#!/usr/bin/env node
// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var CmdParser$Hwan = require("./CmdParser.js");
var CmdRunner$Hwan = require("./CmdRunner.js");

CmdRunner$Hwan.run(CmdParser$Hwan.parse(/* () */0));

/*  Not a pure module */
