// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Sys      = require("bs-platform/lib/js/sys.js");
var $$Array  = require("bs-platform/lib/js/array.js");
var Cli$Hwan = require("./Cli.js");

function getCommandLineArgs(args) {
  if (args) {
    var match = args[1];
    if (match) {
      return match[1];
    } else {
      return /* [] */0;
    }
  } else {
    return /* [] */0;
  }
}

Cli$Hwan.execute(getCommandLineArgs($$Array.to_list(Sys.argv)));

exports.getCommandLineArgs = getCommandLineArgs;
/*  Not a pure module */
