// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Command$Hwan = require("./Command.js");

var command = Command$Hwan.build("build", "Build a package and its dependences or all packages if the package name is omitted.", /* Some */["\n    Build package foo and its dependences\n    $ hwan build foo\n\n    Build all packages\n    $ hwan build\n  "]);

exports.command = command;
/* command Not a pure module */
