// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function build(command, describe, example) {
  return /* record */[
          /* command */command,
          /* describe */describe,
          /* example */example,
          /* exec */(function () {
              console.log("command: " + command);
              console.log("describe: " + describe);
              if (example) {
                console.log("example: ");
                console.log(example[0]);
              }
              return /* Ok */0;
            })
        ];
}

exports.build = build;
/* No side effect */
