// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Command$Hwan = require("./Command.js");

var command = Command$Hwan.build("help", "", /* Some */["\n    Usage: hwan help <command>\n  "]);

exports.command = command;
/* command Not a pure module */
