// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Command$Hwan = require("./Command.js");

var command = Command$Hwan.build("init", "Create a new hwan repository.", /* Some */["\n    Create a new hwan repository for an existing codebase\n    $ cd /path/to/my/codebase\n    $ hwan init\n  "]);

function print(str) {
  console.log(str);
  return /* () */0;
}

exports.command = command;
exports.print   = print;
/* command Not a pure module */
